/**
 * @packageDocumentation
 * @module api.functional.debug.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller DebugController.getHealth
 * @path GET /debug/health
 * @accessor api.functional.debug.health.getHealth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHealth(
  connection: IConnection,
): Promise<getHealth.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHealth.METADATA,
    template: getHealth.METADATA.path,
    path: getHealth.path(),
  });
}
export namespace getHealth {
  export type Output = {
    status: string;
    timestamp: string;
    message: string;
  };

  export const METADATA = {
    method: "GET",
    path: "/debug/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/debug/health";
}
