/**
 * @packageDocumentation
 * @module api.functional.github_app.debug
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as installations from "./installations/index";
