/**
 * @packageDocumentation
 * @module api.functional.github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as webhooks from "./webhooks/index";
