/**
 * @packageDocumentation
 * @module api.functional.logs.executions.recover_missing_logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @tag logs
 * @summary Recover missing logs for completed executions
 * @throws 401 인증 실패
 * @controller LogsController.recoverMissingLogs
 * @path POST /logs/executions/recover-missing-logs
 * @accessor api.functional.logs.executions.recover_missing_logs.recoverMissingLogs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function recoverMissingLogs(
  connection: IConnection,
): Promise<recoverMissingLogs.Output> {
  return PlainFetcher.fetch(connection, {
    ...recoverMissingLogs.METADATA,
    template: recoverMissingLogs.METADATA.path,
    path: recoverMissingLogs.path(),
  });
}
export namespace recoverMissingLogs {
  export type Output = {
    success: boolean;
    message: string;
    error?: undefined | string;
  };

  export const METADATA = {
    method: "POST",
    path: "/logs/executions/recover-missing-logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/logs/executions/recover-missing-logs";
}
