/**
 * @packageDocumentation
 * @module api.functional.logs.ecs.execution
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

export * as runtime from "./runtime/index";

/**
 * @tag logs
 * @summary Get ECS deployment logs by execution ID
 * @throws 400 Invalid execution ID
 * @throws 401 인증 실패
 * @throws 404 Execution not found
 * @controller LogsController.getEcsLogsByExecution
 * @path GET /logs/ecs/execution/:executionId
 * @accessor api.functional.logs.ecs.execution.getEcsLogsByExecution
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEcsLogsByExecution(
  connection: IConnection,
  executionId: string,
  query: getEcsLogsByExecution.Query,
): Promise<getEcsLogsByExecution.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEcsLogsByExecution.METADATA,
    template: getEcsLogsByExecution.METADATA.path,
    path: getEcsLogsByExecution.path(executionId, query),
  });
}
export namespace getEcsLogsByExecution {
  export type Query = {
    limit?: undefined | number;
  };
  export type Output = {
    logs: {
      timestamp: string;
      message: string;
      level: string;
      phase: null | string;
      step: null | string;
      executionType: string;
    }[];
    hasMore: boolean;
  };

  export const METADATA = {
    method: "GET",
    path: "/logs/ecs/execution/:executionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (executionId: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/logs/ecs/execution/${encodeURIComponent(executionId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
