/**
 * @packageDocumentation
 * @module api.functional.logs.executions.check_stale
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @tag logs
 * @summary Check for stale executions
 * @throws 401 인증 실패
 * @controller LogsController.checkStaleExecutions
 * @path POST /logs/executions/check-stale
 * @accessor api.functional.logs.executions.check_stale.checkStaleExecutions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function checkStaleExecutions(
  connection: IConnection,
): Promise<checkStaleExecutions.Output> {
  return PlainFetcher.fetch(connection, {
    ...checkStaleExecutions.METADATA,
    template: checkStaleExecutions.METADATA.path,
    path: checkStaleExecutions.path(),
  });
}
export namespace checkStaleExecutions {
  export type Output = {
    checked: number;
    updated: number;
    message: string;
  };

  export const METADATA = {
    method: "POST",
    path: "/logs/executions/check-stale",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/logs/executions/check-stale";
}
